version: '3.8'
services:

  slack-bot_mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_ROLE=readWrite
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
      - TZ
    expose:
      - 27017
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  reddit-scraper:
    build:
      context: ./reddit_scraper
      dockerfile: Dockerfile
    environment:
      - MONGO_COLLECTION
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
      - MONGO_SETTINGS
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_PASSWORD
      - REDDIT_USERNAME
      - SCRAPER_HC_UUID
      - TZ
    depends_on:
      - slack-bot_mongo-db

  slack-bot:
    build:
      context: ./slack_bot
      dockerfile: Dockerfile
    environment:
      - SLACK_TOKEN
      - BOT_ID
      - BOT_CHANNEL
      - USER_ID
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_COLLECTION
      - MONGO_SETTINGS
      - SLACK_HC_UUID
      - TZ
    depends_on:
      - slack-bot_mongo-db
