version: '3.8'
services:

  slack-bot_mongo-db:
    container_name: slack-bot_mongo-db-dev
    volumes:
      - dev-mongodb-slackbot:/data/db

  reddit-scraper:
    container_name: reddit-scraper-dev
    environment:
      - DEV_RUN

  slack-bot:
    container_name: slack-bot-dev
    environment:
      - DEV_RUN

volumes:
  dev-mongodb-slackbot:
    external:
      name: dev-mongodb-slackbot
