version: '3.8'
services:

  mongodb:
    container_name: slack-bot_mongodb-dev
    volumes:
      - dev-mongodb-slackbot:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  reddit-scraper:
    container_name: reddit-scraper-dev
    environment:
      - DEV_RUN

  bot:
    container_name: slack-bot-dev
    environment:
      - DEV_RUN

volumes:
  dev-mongodb-slackbot:
    external:
      name: dev-mongodb-slackbot
